name: physics-sim
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py311h6771f6e_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py311hee243d0_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.22.0=hb83781b_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_impl_osx-arm64=1030.6.3=llvm19_1_he8a363d_4
  - cctools_osx-arm64=1030.6.3=llvm19_1_h6d92914_4
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - clang=19.1.7=default_hf9bcbb7_7
  - clang-19=19.1.7=default_hf3020a7_7
  - clang_impl_osx-arm64=19.1.7=default_hc11f16d_7
  - clang_osx-arm64=19.1.7=h75f8d18_31
  - cli11=2.6.0=h248ca61_0
  - click=8.3.1=pyh8f84b5b_1
  - compiler-rt=19.1.7=h855ad52_1
  - compiler-rt_osx-arm64=19.1.7=he32a8d3_1
  - contourpy=1.3.3=py311h7d85929_4
  - cpython=3.11.14=py311hd8ed1ab_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyclopts=4.5.2=pyhcf101f3_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - double-conversion=3.3.1=h286801f_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastapi=0.129.0=hccfc660_0
  - fastapi-cli=0.0.23=pyhcf101f3_0
  - fastapi-core=0.129.0=pyhcf101f3_0
  - fenics-basix=0.10.0=py311ha99e8d3_0
  - fenics-basix-nanobind-abi=2.16=py310hf7f2cdb_0
  - fenics-dolfinx=0.10.0=py311hc730058_101
  - fenics-ffcx=0.10.1=pyh1e3ed43_0
  - fenics-libbasix=0.10.0=py311haf9c301_0
  - fenics-libdolfinx=0.10.0=py311h0e29e79_101
  - fenics-ufcx=0.10.1=haec879b_0
  - fenics-ufl=2025.2.1=pyhcf101f3_0
  - fftw=3.3.10=mpi_mpich_h6eb47b5_11
  - fmt=11.2.0=h440487c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.7.0=py311h8740443_0
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=haf38c7b_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=mpi_mpich_h15328f7_6
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311h9408147_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=3.1.0=h54b5d9f_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jsoncpp=1.9.6=h726d253_1
  - kahip=3.19=py311hd5598a6_1
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.18=hdfa7624_0
  - ld64=956.6=llvm19_1_he86490a_4
  - ld64_osx-arm64=956.6=llvm19_1_ha2625f7_4
  - lerc=4.0.0=hd64df32_1
  - libadios2=2.10.2=mpi_mpich_hf66b461_14
  - libaec=1.1.5=h8664d51_0
  - libamd=3.3.3=h5087772_7100102
  - libblas=3.11.0=5_h51639a9_openblas
  - libboost=1.88.0=h18cd856_6
  - libboost-devel=1.88.0=hf450f58_6
  - libboost-headers=1.88.0=hce30654_6
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libbtf=2.3.2=h99b4a89_7100102
  - libcamd=3.3.3=h99b4a89_7100102
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libccolamd=3.3.4=h99b4a89_7100102
  - libcholmod=5.3.1=hbba04d7_7100102
  - libclang-cpp19.1=19.1.7=default_hf3020a7_7
  - libclang13=21.1.8=default_h13b06bd_3
  - libcolamd=3.3.4=h99b4a89_7100102
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.4=hf6b4638_0
  - libfabric=2.4.0=hce30654_1
  - libfabric1=2.4.0=h84a0fba_1
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libglib=2.86.2=he69a767_0
  - libhwloc=2.12.2=default_ha3cc4f2_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - libklu=2.3.5=h4370aa4_7100102
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.8=h8e0c9ce_0
  - liblzma=5.8.2=h8088a28_0
  - libnetcdf=4.9.3=nompi_h7a8d41e_104
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.55=h132b30e_0
  - libpq=18.1=h944245b_2
  - libptscotch=7.0.10=int32_hf99fa1b_2
  - libscotch=7.0.10=int32_hed6a4d5_2
  - libsigtool=0.1.3=h98dc951_0
  - libsodium=1.0.20=h99b78c6_0
  - libspqr=4.3.4=h775d698_7100102
  - libsqlite=3.51.2=h1b79a29_0
  - libssh2=1.11.1=h1590b86_0
  - libsuitesparseconfig=7.10.1=h4a8fc20_7100102
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.1=h4030677_1
  - libumfpack=6.3.5=h7c2c975_7100102
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvm-tools=19.1.7=h855ad52_2
  - llvm-tools-19=19.1.7=h91fd4e7_2
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metis=5.1.0=h15f6cfe_1007
  - mpi=1.0.1=mpich
  - mpi4py=4.1.1=py311h3f6cb2c_102
  - mpich=4.3.2=hb31c3fa_105
  - msgpack-python=1.1.2=py311h5a5e7c7_1
  - multidict=6.7.0=py311h97ccca8_0
  - mumps-include=5.8.1=ha6078a4_4
  - mumps-mpi=5.8.1=h3d714e2_4
  - munkres=1.1.4=pyhd8ed1ab_1
  - nanobind-abi=16=hd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nlohmann_json=3.12.0=h784d473_1
  - numpy=2.4.2=py311had1e860_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - parmetis=4.0.3=ha4b917a_1007
  - pcre2=10.46=h7125dd6_0
  - petsc=3.24.4=real_h9fb0cc7_0
  - petsc4py=3.24.4=np2py310h37723c0_0
  - pillow=12.1.1=py311hd37aea2_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pkg-config=0.29.2=hde07d2e_1009
  - platformdirs=4.9.2=pyhcf101f3_0
  - pooch=1.9.0=pyhd8ed1ab_0
  - proj=9.7.1=hfb14a63_3
  - propcache=0.3.1=py311h4921393_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311h71babbd_1
  - pydantic-extra-types=2.11.0=pyhcf101f3_1
  - pydantic-settings=2.13.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h18782d2_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.11.14=hd8ed1ab_3
  - python-multipart=0.0.22=pyhcf101f3_0
  - python_abi=3.11=8_cp311
  - pyvista=0.47.0=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311hc290fe0_1
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.9.3=hb266e41_0
  - readline=8.3=h46df422_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.2=pyhcf101f3_0
  - rich-rst=1.3.2=pyhd8ed1ab_0
  - rich-toolkit=0.19.4=pyhcf101f3_0
  - scalapack=2.2.0=h1b9cfae_5
  - scipy=1.17.0=py311he9931d0_1
  - scooby=0.11.0=pyhd8ed1ab_0
  - sdkroot_env_osx-arm64=26.0=ha3f98da_6
  - setuptools=82.0.0=pyh332efcf_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sigtool-codesign=0.1.3=h98dc951_0
  - six=1.17.0=pyhe01879c_1
  - slepc=3.24.2=real_hc5a9acf_0
  - slepc4py=3.24.2=np2py310h0c2cbfb_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - spdlog=1.15.3=h217a1f9_1
  - sqlite=3.51.2=h85ec8f2_0
  - starlette=0.52.1=pyhfdc7a7d_0
  - superlu=7.0.0=h742a510_1
  - superlu_dist=9.1.0=h89afcdd_0
  - tapi=1600.0.11.8=h997e182_0
  - tbb=2022.3.0=h4ddebb9_2
  - tk=8.6.13=h010d191_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py311h9408147_0
  - typer=0.24.0=pyhcf101f3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.1=py311hc949640_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - utfcpp=4.09=hce30654_0
  - uvicorn=0.41.0=pyhc90fa1f_0
  - uvicorn-standard=0.41.0=he9f3e0c_0
  - uvloop=0.22.1=py311h9408147_1
  - vtk-base=9.5.2=py311hd5fd623_1
  - watchfiles=1.1.1=py311h0f0954d_0
  - websockets=16.0=py311he363849_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - wslink=2.5.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py311ha9b3269_0
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=ha86207d_5
  - zlib-ng=2.3.3=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/joan.vendrell/miniforge3/envs/physics-sim
